name: ProjectNextDaVinci
favicon: null
layout_spectrum: 0.9060885428916663
typography_spectrum: 0.46991
title: Who will be the next DaVinci?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b4b4b4'
    - '#757575'
    - '#373737'
    - '#b22828'
  brandStrength: 0.7541742157191038
  lightness: 0.625
  saturation: 0.4696468226611614
  rhythmicContrast: 0.6611750507727265
purpose: []
